kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: changelog-backend-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
